version: "3.9"

services:
  db:
    restart: always
    image: postgres:14.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    restart: unless-stopped
    container_name: django_web
    command: bash -c "chmod +x /code/docker-entry-point.sh && /code/docker-entry-point.sh"
    volumes:
      - ./data/usersfiles:/code/usersfiles
      - ./data/media:/code/media
      - ./data/staticfiles:/code/staticfiles
      - ./data/logs:/code/logs
    ports:
      - "8080:8080"
    environment:
      - DJANGO_ENV=production
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
volumes:
    pgdata:
