# Generated by Django 4.1.4 on 2023-01-11 21:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Name",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Who added",
                    ),
                ),
            ],
            options={
                "verbose_name": "Name",
                "verbose_name_plural": "Names",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo", models.ImageField(upload_to="", verbose_name="Photo")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, default=Decimal("0.0"), max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, default=Decimal("0.0"), max_digits=9, verbose_name="Longitude"
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True, verbose_name="Upload date")),
                (
                    "names",
                    models.ManyToManyField(related_name="photos", to="api.name", verbose_name="People on the photo"),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.AddConstraint(
            model_name="name",
            constraint=models.UniqueConstraint(fields=("name", "owner"), name="unique_name_for_user"),
        ),
    ]
