# Generated by Django 4.1.4 on 2023-01-11 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Owner profile"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to=pathlib.PureWindowsPath(
                    "C:/Users/ou170/Desktop/my projects/photos-test-task/photos/media/photos"
                ),
                verbose_name="Photo",
            ),
        ),
    ]
