# Generated by Django 4.1.4 on 2023-01-11 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_photo_owner_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Who added"
            ),
        ),
    ]
